### ISSUE TITLE
[BUG] ConnectorNotFoundError when window.ethereum contains two wallet flags

### ISSUE THREAD

**Issue by shmakovigor** [family/connectkit#260]
**Describe the bug**

When `window.ethereum` contains two wallet flags (such as `isMetaMask` and `isZerion`, for example), the SDK throws the following error: **ConnectorNotFoundError**. As a result, the user is currently unable to connect their wallet.

**To reproduce**

- Open [https://docs.family.co/connectkit](https://docs.family.co/connectkit)
- Make sure that injected wallet `window.ethereum` contains two wallet flags (`isMetaMask` and `isZerion`)
- Click "Connect Wallet"

**Expected behavior**

The SDK should not disregard wallets that have their own wallet flag and the flag `isMetamask`. This is because many dApps only work with MetaMask, which is why wallets include this additional flag for compatibility purposes. If the SDK detects a flag other than MetaMask, it should that one instead.

**Screenshots**

<img src="https://github.com/wagmi-dev/wagmi/assets/10052224/65d29bb2-860d-4ffc-b05a-5a25dcc056cb" width="300"/>

**Comment by daedboi** [comment]
We are experiencing the same issue, waiting on a fix

**Comment by lochie** [comment]
The problem here is the secondary wallet trying to override MetaMask connectivity which stops MetaMask being able to be used. This is something we're actively looking to resolve both [in ConnectKit](https://github.com/family/connectkit/pull/256) and via [EIP-6963](https://eips.ethereum.org/EIPS/eip-6963).

PR #256 will hopefully resolve this for most wallets, but we can't guarantee _every_ wallet until IEP-6936 is in prod.

We do currently have manual detections per-wallet to avoid this collision, but unfortunately it is manual so we can only add updates as they are needed.

https://github.com/family/connectkit/blob/00716ee5117054c8794cf191036841b41c387287/packages/connectkit/src/utils/index.ts#L95-L124

**Comment by lochie** [comment]
We've done some updates to injected connectors in version `1.5.1` which might resolve this problem. @shmakovigor if this still persists please let us know 🙏
