### ISSUE TITLE
[BUG] Chrome thinks metamask not installed if phantom also installled

### ISSUE THREAD

**Issue by omarperacha** [family/connectkit#376]
**Describe the bug**

When selecting "MetaMask" from the wallet selection modal on Chrome, if Phantom wallet is also installed, "Install MetaMask" modal is shown instead of opening MetaMask.

**To reproduce**

Chrome browser with both Phantom and MetaMask extensions installed. Click "connect wallet" -> "MetaMask", ConnectKit v1.4.0

**Expected behaviour**

MetaMask extension should open with a connection request

**Screenshots**

![WhatsApp Image 2024-04-07 at 15 14 35](https://github.com/family/connectkit/assets/26068338/c3f2677d-79f0-4065-932e-5c9682ae35e6)

**Environment details**

MacOS Sonoma 14.4.1, Intel Mac, Chrome Version 123.0.6312.107

Can not currently confirm if this issue is confined to Phantom only, or if any other EVM wallets would lead to the same issue

**Comment by lochie** [comment]
@omarperacha This should be resolved since [ConnectKit `1.6.0`](https://family.co/changelog/2024-01-10) as we've migrated to EIP-6963, but this will still occur for dapps that have not yet migrated to this version.

If you're using wagmi v1 in your app you should be able to use ConnectKit 1.6.0 without any breaking changes, if you're using wagmi v2 then you'll want to use ConnectKit 1.7.0 and above (migration guide [here](https://docs.family.co/connectkit/migration-guide#section-170-breaking-changes-update-packages)).

Another reason this occurs for you is that this is actually an option with Phantom's extension settings for dapps that don't support EIP-6963.

<img width="395" alt="CleanShot —04-08 at 00 53 46@2x" src="https://github.com/family/connectkit/assets/1930210/acdc8dda-2a9b-4c92-9ded-869701460b11">
