### ISSUE TITLE
[BUG] Browser wallet doesn't connect inside iframe on mobile

### ISSUE THREAD

**Issue by ryanberckmans** [family/connectkit#410]
**Describe the bug**

Injected Browser Wallet doesn't connect when the connection attempt occurs inside an iframe on a webpage on a mobile browser.

The impact here is that mobile wallet browser users can't buy crypto conference tickets using the payment iframe inside the ticketing website, they need to use desktop.

**To reproduce**

1. Go to this link on desktop https://ryanberckmans.github.io/block-proposal-frequency/test.html --> click Pay --> click Browser Wallet --> your wallet will connect successfully to the iframe inside the page.
2. Do the same thing in a mobile wallet browser, such as MetaMask Mobile Browser or Coinbase Wallet Mobile Browser, and instead of connecting successfully, the Browser Wallet will pop-up a QR code and never connect.

**Expected behavior**

I expect the browser wallet to be successfully connected inside the iframe on mobile.

**Screenshots**

![image](https://github.com/family/connectkit/assets/299324/86c9fec7-1995-4dff-bbc1-3c23ac7678ed)

**Environment details**

- connectkit 1.8.2
- wagmi 2.10.9

**Comment by lochie** [comment]
This would be more of an issue on the wallet's side as they need to inject their provider into the iframe window as well. Extensions do this automatically which is why this works on desktop fine.

I would suggest trying to get in contact with the wallets you want to support this feature, though this may be a limitation due to iframes and security policies, so it maybe something that is impossible to support.
