### ISSUE TITLE
[BUG] Production build is failing with latest version connectkit@1.1.2

### ISSUE THREAD

**Issue by lykalabrada** [family/connectkit#89]
**Describe the bug**

Production build is failing with error `ReferenceError: _a is not defined`. Tricky to debug, as this is working well on development mode.
This is only happening when I updated my connectkit version to `^1.1.2`

**To reproduce**

Using connectkit and wagmi versions, and client configuration below:
```
/* package.json */
"connectkit": "^1.1.2",
"wagmi": "^0.10.15"
```
```
const client = createClient(
  getDefaultClient({
    autoConnect: true,
    appName: "Test wallet connection",
    connectors: [new MetaMaskConnector()]
  })
);
```
Run the production build.

**Expected behavior**

There should be no issue when running the production build. Again, it is working fine with no issue when ran on development mode.

**Screenshots**

<img width="1713" alt="image" src="https://user-images.githubusercontent.com/17063281/214591963-1ee1913b-639c-47b2-8772-bf05f31e0434.png">

**Environment details**

If applicable, let us know which OS, browser, browser version etc you're using.

**Additional context**

As a workaround, I'm temporarily using `connectkit@1.1.1` and `wagmi@0.10.15`

**Comment by beyondthecode-bc** [comment]
It's impossible to work well on development. Probably, you have package lock or yarn lock present and no upgrade was performed. If you manually yarn add wagmi@latest and conneckit@latest and run yarn dev, your dev build will also fail.

**Comment by lykalabrada** [comment]
@beyondthecode-bc I already tried deleting the lock file, node modules, cache.. everything that might lock up the version. 

For additional info, we are using [pnpm](https://pnpm.io/) and nextjs.

**Comment by alagunoff** [comment]
Confirm this problem, have the same one. Came across this problem yesterday and couldn't debug it so switched to previous packages versions. Wanted to write about this problem but didn't know where to write, to wagmi repository or here)

**Comment by beyondthecode-bc** [comment]
> @beyondthecode-bc I already tried deleting the lock file, node modules, cache.. everything that might lock up the version.
> 
> For additional info, we are using [pnpm](https://pnpm.io/) and nextjs.

Strage. I don't use pnpm (yet). Stuck with yarn and npm. Additionally, I run **Node.js v16.18.0**

**Comment by lykalabrada** [comment]
@alagunoff, fortunately I have no issues on production build when using `connectkit@1.1.1` + `wagmi@0.10.15` combination

**Comment by lochie** [comment]
Hey everyone, we believe that ConnectKit version `1.1.2` has an issue with Next 13, which we're looking into fixing immediately. If anyone here is **not** using Next 13 please let us know as this will help us debug this error.

**Comment by nikmace** [comment]
Thanks for catching this issue @lykalabrada, we also have the same problem with deployment. Will be waiting for a fix.

**Comment by 70nyIT** [comment]
Yep, confirm same problem on my side

**Comment by lochie** [comment]
Just a quick update while we continue investigating the issue:

We've found that [`swcMinify: true`](https://nextjs.org/docs/advanced-features/compiler#minification) in Next 13 is causing us some issues. If you wish to use the new features in ConnectKit `1.1.2` right now a quick workaround might be to set this to `false` in your Next config. If this doesn't resolve the issue please let us know so we know to dive deeper into finding the root cause of this problem.

Thanks everyone for letting us know they're having similar issues, we appreciate everyones contribution to keeping ConnectKit awesome 🫡
We're still investigating further and we will keep this thread updated as we find more information to resolve this issue properly.

**Comment by alagunoff** [comment]
@lochie Thanks for the update. Confirm that with `swcMinify: false` in next config everything works just fine. Project setting is `connectkit@1.1.2` + `wagmi@0.10.15` + `next@13.1.5`

**Comment by META-DREAMER** [comment]
Also ran into this today. In the future if you are updating a minor version of wagmi you should also update the minor version in connectkit (e.g. v1.2.0 instead of v1.1.2) so people who have installed older versions dont automatically get updated to a newer one with breaking changes

**Comment by lochie** [comment]
Very good point @META-DREAMER, we will be more vigilant with our semver logic moving forward.

**Comment by lochie** [comment]
Looks like our dev and prod rollup configs were mismatched, where prod had Terser set up which has issues with `swcMinify: true`. We didn't catch this because previous builds weren't having any issues up until now where the latest update has some new patterns that we weren't using previously, which Terser doesn't seem to compress properly, and our build tests also didn't pick this up runtime issue.

I've opened PR https://github.com/family/connectkit/pull/94 which should resolve this issue, just waiting on some internal reviews before moving forward.
Thanks for holding tight, hoping to have the npm package resolved soon!

**Comment by lochie** [comment]
Hey all! We've pushed a version of ConnectKit that is now compatible with Nextjs 13's default configuration.
Please upgrade to ConnectKit version `1.1.3` and let us know if you have any further issues, thanks!

**Comment by alagunoff** [comment]
> Hey all! We've pushed a version of ConnectKit that is now compatible with Nextjs 13's default configuration. Please upgrade to ConnectKit version `1.1.3` and let us know if you have any further issues, thanks!

Great news, thanks! Now waiting for updating peerDependency to `wagmi@0.11.x` :)
